
# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

# Uncomment this line if you're using Swift

use_frameworks!
inhibit_all_warnings!
target '网络数据处理' do
    #微信SDK
    #pod 'WechatOpenSDK'
    #swift库
    #布局
    pod 'SnapKit'
    #网络请求
    pod 'Alamofire'
    #网络缓存
    pod 'DaisyNet'
    #网络指示
    pod 'AlamofireNetworkActivityIndicator'
    #HUD
    #pod 'PKHUD'
    #图片缓存库
    pod 'Kingfisher'
    #轮播图
    #pod 'LLCycleScrollView'
    #键盘处理
    #pod 'IQKeyboardManagerSwift'
    #cell复用
    pod 'Reusable'
    #初始化
    pod 'Then'
    #无数据指示
    pod 'EmptyDataSet-Swift'
    #推流库
    #pod 'LFLiveKit'
    #刷新库
    pod 'MJRefresh'
    #照片库工具
    #pod 'ZLPhotoBrowser'
    #MQTT库
    #pod 'MQTTClient'
    #播放库
    #pod 'ijkplayer'
    # 分享主模块(必须)
    #pod 'mob_sharesdk'
    # UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
    #pod 'mob_sharesdk/ShareSDKUI'
    # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
    #pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
    #pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
    #//（微信sdk带支付的命令，和上面不带支付的不能共存，只能选择一个）
    #pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'
    # 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
    #pod 'mob_sharesdk/ShareSDKExtension'
end



